config/routes.rb
Flickr::Application.routes.draw do

  root to: 'general#index'

  post 'flickr/search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flickr_controller.rb
class FlickrController < ApplicationController
  require 'open-uri'

  def search
    # Tags for search
    tags = URI.escape(params[:q].mb_chars.downcase.to_s.gsub(' ', ','))

    # Flickr url
    url = "http://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=#{FLICKR_API_KEY}&tags=#{tags}&safe_search=1&per_page=20"

    # Get xml flickr photos
    xml = Rails.cache.fetch("flickr_search_#{tags}") { open(url).read }

    photos = Nokogiri::XML(xml)

    @photos = photos.xpath('//photo')
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/views/flickr/_photos.erb
<% if @photos.any? %>
  <% @photos.each do |photo| %>
    <%= image_tag("http://farm#{photo.attr('farm')}.staticflickr.com/#{photo.attr('server')}/#{photo.attr('id')}_#{photo.attr('secret')}.jpg") %>
  <% end %>
<% else %>
  По Вашему запросу ничего не найдено!
<% end %>

app/views/flickr/search.js.erb
$('#flickr-result').html('<%= escape_javascript(render('flickr/photos')) %>');

app/views/general/index.html.erb
<%= form_tag flickr_search_path, remote: true do %>

  <%= text_field_tag :q %>

  <%= submit_tag 'Найти' %>

<% end %>

<div id="flickr-result"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>